### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by ziabary** [mironov/react-redux-loading-bar#56]
Just installed react-redux-loading-bar in a kriasoft/starterkit-redux based application and I got following error:
```
TypeError: Cannot read property 'default' of undefined
at Function.mapStateToProps [as mapToProps] (/XXX/node_modules/react-redux-loading-bar/build/loading_bar.js:250:30)
at mapToPropsProxy (/XXX/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
at Function.detectFactoryAndVerify (/XXX/node_modules/react-redux/lib/connect/wrapMapToProps.js:63:19)
at mapToPropsProxy (/XXX/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
at handleFirstCall (/XXX/node_modules/react-redux/lib/connect/selectorFactory.js:37:18)
at pureFinalPropsSelector (/XXX/node_modules/react-redux/lib/connect/selectorFactory.js:85:81)
at Object.runComponentSelector [as run] (/XXX/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
at Connect.initSelector (/XXX/node_modules/react-redux/lib/components/connectAdvanced.js:195:23)
at new Connect (/XXX/node_modules/react-redux/lib/components/connectAdvanced.js:136:15)
at resolve (/XXX/node_modules/react-dom/cjs/react-dom-server.node.development.js:2086:14)
```

**Comment by joelcollyer** [comment]
I encountered this too. Make sure you update your reducer to include the loading bar:

```
import { loadingBarReducer } from 'react-redux-loading-bar'

export default combineReducers({
  // ...
  loadingBar: loadingBarReducer,
});
```

**Comment by mironov** [comment]
@joelcollyer Thank you for answering this question.

@ziabary Is your issue resolved? Have you installed loading bar reducer?

**Comment by ziabary** [comment]
@joelcollyer : Thanks for your reply it was solved
@mironov: The problem was that I didn't include "loadingBar" as reducer name. Following code fails: 

'''
import { loadingBarReducer } from 'react-redux-loading-bar'

const rootReducer = combineReducers({
  // ...
  loadingBarReducer,
})

export default rootReducer
''''

**Comment by mironov** [comment]
@ziabary Thank you for sharing that. Glad your issue is resolved. I'm going to close it.
